### PR TITLE
Added setting aliases for points through admin map view and credentials/permissions with different views

### PR DESCRIPTION
**Pull request by pappikatla**

### CODE REVIEW

**Comment by tmwbook** [comment]
Currently not committing the changes to database.  Could be a load or save issue

**Comment by tmwbook** [comment]
Its an issue with saving AND loading.  FakePoint only supports a String for name and Aliases needs an ArrayList<String> to work.  This is probably indicative of problems that exist with the loading/conversion step which we will need to ensure are working correctly.

**Comment by pappikatla** [comment]
The issue was that when we called getAllPoints when loading the map we called deep clone which called getName instead of getNames only returning the first name of the point

**Comment by backslash166** [comment]
This needs to be updated before it can be accepted, there are merge conflicts.

**Review by tmwbook — CHANGES_REQUESTED** [review]
In confirmation for Singup class we need to change the password field to not plain text and add a listener to the boxes so the admin can hit enter and it will confirm the account creation

**Review by tmwbook — APPROVED** [review]

**Pull request merged**
